//Conflict

### Get conflicts
GET https://conflicttracker-production-b460.up.railway.app/api/v1/conflicts
Accept: application/json

### Create conflict id 3
POST https://conflicttracker-production-b460.up.railway.app/api/v1/conflicts
Content-Type: application/json

{
  "id": 3,
  "name": "Test Conflict Railway",
  "startDate": "2024-01-01",
  "status": "ACTIVE",
  "description": "Conflicto de prueba creado desde IntelliJ"
}

### Delete conflict id 3
DELETE https://conflicttracker-production-b460.up.railway.app/api/v1/conflicts/3

