spring:
  application:
    name: ConflictTracker

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:conflict-tracker}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:embedded}

  h2:
    console:
      enabled: ${SPRING_H2_CONSOLE_ENABLED:true}
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: ${PORT:8080}
